#!/usr/bin/env bash

exitf() {
    [[ -z `jobs -r` ]] || kill 0
    rm -f pipe0 pipe1
}

trap exitf EXIT

if [[ -z $@ ]]
then
    n_games=1
    players="player_smart.py"
else
    n_games=$1
    shift
    players=$@
fi

mkfifo pipe0 pipe1

./run_tournament.py ${n_games} player_manual3.py ${players} 2>logerr &

IFS=
cat pipe1 | while read -r line ; do echo -e $line ; done &
cat > pipe0
